CREATE TABLE cht_chat(
	messageId BINARY(32) PRIMARY KEY NOT NULL,
	username VARCHAR(300) NOT NULL DEFAULT 'Anonymous',
	text VARCHAR(300) NOT NULL DEFAULT '',
	insertDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)